version: '2'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  users:
    image: cimbonda/aelastic-xspot-users:latest
    depends_on:
      - kafka
    ports:
      - 3113:3113
#    environment:
#      - BOOTSTRAP_SERVERS: '0.0.0.0:9092'

#  notifications:
#    image: cimbonda/aelastic-xspot-notifications:latest
#    depends_on:
#      - broker
#    ports:
#      - 3114:3114
